/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package metodosnumericoscomun;

import Menu.Menu;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import metodosnumericosraices.PruebaB;

/**
 *
 * @author adria
 */
public class InterfaceBiseccion extends javax.swing.JFrame {

    /**
     * Creates new form Interface
     */
    public InterfaceBiseccion() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        textField1 = new java.awt.TextField();
        textField2 = new java.awt.TextField();
        textField3 = new java.awt.TextField();
        textField4 = new java.awt.TextField();
        textField5 = new java.awt.TextField();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        textField7 = new java.awt.TextField();
        jLabel11 = new javax.swing.JLabel();
        panel = grafica.obtieneGrafica();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bisección ");
        setBackground(new java.awt.Color(255, 255, 51));
        setMaximumSize(new java.awt.Dimension(1000, 390));
        setMinimumSize(new java.awt.Dimension(1000, 390));
        setPreferredSize(new java.awt.Dimension(1000, 390));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(600, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));
        jPanel1.setLayout(null);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 108, 0, 0);
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 192, 0, 0);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 323, 0, 0);

        jLabel5.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel5.setText("FUNCIÓN ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 80, 70, 22);

        jLabel6.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel6.setText("X1");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(80, 110, 30, 24);

        jLabel7.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel7.setText("X2");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(80, 140, 30, 24);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 102, 0));
        jLabel8.setText("MÉTODO DE BISECCIÓN");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 10, 317, 35);

        jLabel1.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel1.setText("ERROR");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 200, 47, 24);

        jLabel9.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel9.setText("RAIZ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 270, 32, 24);

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calcular");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 320, 100, 30);

        textField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textField1ActionPerformed(evt);
            }
        });
        jPanel1.add(textField1);
        textField1.setBounds(110, 80, 277, 20);
        jPanel1.add(textField2);
        textField2.setBounds(110, 140, 60, 20);
        jPanel1.add(textField3);
        textField3.setBounds(110, 110, 60, 20);
        jPanel1.add(textField4);
        textField4.setBounds(110, 200, 160, 20);

        textField5.setBackground(new java.awt.Color(255, 255, 255));
        textField5.setEditable(false);
        textField5.setEnabled(false);
        textField5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jPanel1.add(textField5);
        textField5.setBounds(80, 260, 260, 30);

        jLabel10.setFont(new java.awt.Font("Dubai Light", 1, 14)); // NOI18N
        jLabel10.setText("ITERACIONES");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(10, 160, 100, 40);

        jButton2.setBackground(new java.awt.Color(0, 255, 153));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Limpiar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(150, 320, 100, 30);

        jButton3.setBackground(new java.awt.Color(255, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Salir");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(280, 320, 100, 30);
        jPanel1.add(textField7);
        textField7.setBounds(110, 170, 60, 20);

        jLabel11.setFont(new java.awt.Font("Dubai Light", 1, 18)); // NOI18N
        jLabel11.setText("Ingrese los datos requeridos a continuación.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(20, 50, 370, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 407, 364);

        panel.setLayout(null);
        getContentPane().add(panel);
        panel.setBounds(413, 0, 567, 317);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("  Desde");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(423, 323, 50, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(477, 319, 80, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel13.setText("Hasta");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(567, 328, 40, 20);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(611, 319, 90, 30);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("intervalos de");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(705, 331, 74, 15);
        getContentPane().add(jTextField3);
        jTextField3.setBounds(783, 319, 84, 30);

        jButton4.setText("Graficar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(877, 323, 93, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textField1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String def;
        def = textField1.getText();
        try {
        double xx0=Double.parseDouble(textField2.getText());
        double xx1=Double.parseDouble(textField3.getText());
        double t=Double.parseDouble(textField4.getText());
        int i=Integer.parseInt(textField7.getText());
        
        IFuncion funcion = new Funcion(def);
        PruebaB b= new PruebaB(funcion);
        double r;
        r=b.raiz(xx0, xx1, t, i);
        textField5.setText(""+ r);
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "Datos incorrectos, favor de verificar.");
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        textField1.setText("");
        textField2.setText("");
        textField3.setText("");
        textField4.setText("");
        textField5.setText("");
        textField7.setText("");
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        this.dispose();
        Menu men = new Menu();
        men.setVisible(true);
        
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String def = textField1.getText();
            double x0 = Double.parseDouble(jTextField1.getText());
            double xn = Double.parseDouble(jTextField2.getText());
            double d = Double.parseDouble(jTextField3.getText());
            FuncionGrafica f= new FuncionGrafica(def);
            double[] x= f.rango(x0, xn, d);
            double[] y = f.eval(x);
            
            grafica.crearGrafica(def, x, y);
        } catch (Exception ex) {
            Logger.getLogger(InterfaceBiseccion.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            String def = "0" ;
            
            double x0 =Double.parseDouble(jTextField1.getText());
            double xn = Double.parseDouble(jTextField2.getText());
            double d = Double.parseDouble(jTextField3.getText()) ;
            FuncionGrafica f= new FuncionGrafica(def);
            double[] x= f.rango(x0, xn, d);
            double[] y = f.eval(x);
            
            grafica.agregarGrafica(def, x, y);
        } catch (Exception ex) {
            Logger.getLogger(InterfacePuntoFijo.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
            String def = "0" ;
            
            double x0 =Double.parseDouble(jTextField1.getText());
            double xn = Double.parseDouble(jTextField2.getText());
            double d = Double.parseDouble(jTextField3.getText()) ;
            FuncionGrafica f= new FuncionGrafica(def);
            double[] x= f.rango(x0, xn, d);
            double[] y = f.eval(x);
            
            grafica.agregarGrafica(def, x, y);
        } catch (Exception ex) {
            Logger.getLogger(InterfacePuntoFijo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceBiseccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceBiseccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceBiseccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceBiseccion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceBiseccion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel panel;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    private java.awt.TextField textField4;
    private java.awt.TextField textField5;
    private java.awt.TextField textField7;
    // End of variables declaration//GEN-END:variables
Grafica grafica= new Grafica ("GRAFICA DE LA FUNCION", "X" ,"Y");
}
